/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function City(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/city.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position = {[0, 0, -15]}scale={[30*6, 1*3, 20*6]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/city.glb')
