/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'


export default function NotSoCyberTruckTruck({position}) {
  const group = useRef()

  const [isHovering, setIsHovering] = useState(false)
  const [isClicked, setIsClicked] = useState(false)

  const { nodes, materials } = useGLTF('/notSoCyberTruckTruck.glb')
  return (
    <group ref={group} dispose={null} scale={.7} onPointerDown={(e) => {setIsClicked(!isClicked)}}
    onPointerOver={(e) => {setIsHovering(true)}} 
    onPointerOut={(e) => {setIsHovering(false)}} position={[position["x"], position["y"], position["z"]-4]}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials.Window} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials.FrontLightBar} />
      <mesh geometry={nodes.Cube001_4.geometry} material={materials.RearLightBar} />
      <mesh geometry={nodes.Cube001_5.geometry} material={materials.GarageDoor} />
    </group>
  )
}

useGLTF.preload('/notSoCyberTruckTruck.glb')
