/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function F15Ver2({position}) {
  const group = useRef()

  const { nodes, materials } = useGLTF('/f15Ver2.glb')
  return (
    <group ref={group} dispose={null}>
      <group scale={0.07} position={[position["x"], position["y"], position["z"]]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Aircraft} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Cockpit} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.Thrusters} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.Hidden} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials.MovableParts} />
      </group>
    </group>
  )
}

useGLTF.preload('/f15Ver2.glb')
